#!/usr/bin/env sh

if [ $(id -u) != "0" ]
then
echo 'must be run as root'
exit 1
fi

O="$(mktemp /tmp/update.out.XXXXXXXX)"
E="$(mktemp /tmp/update.err.XXXXXXXX)"

function _exit ( ) {
  rm -f "$O" "$E"
  exit "$1"
}

function _do ( ) {
  "$@" 1>"$O" 2>"$E"
  _check "$?"
}

function _check ( ) {
  if [ "$1" -ne 0 ] ; then
    echo '! NONZERO RETURN CODE'
    echo ' > There was an error!'
    >&1 cat "$O"
    >&2 cat "$E"
    _exit "$1"
  fi
}

function _trap ( ) {
  echo '! TRAP'
  echo ' > There was an error!'
  _exit 70;
}

trap _trap SIGHUP SIGINT SIGTERM

function i ( ) {
  echo "Installing $@"
  _do pacman -S --needed --noconfirm "$@"
}

i highlight atool w3m poppler libcaca

i xorg-xrdb \
inotify-tools \
libnotify \
gvim \
firefox \
evince

i python-six \
python-lxml \
python-jedi \
python-docopt \
python-pygments \
python-networkx \
python-numpy \
python-sympy \
python-matplotlib \
python-scipy \
python-pillow \
python-cssselect \
autopep8

i python2-xlib

i ffmpeg vlc
i youtube-dl atomicparsley

# useful
i testdisk \
pstoedit python2-numpy python2-lxml \
inkscape \
ack \
the_silver_searcher \
at \
acpi \
udevil \
ntp \
fasd

# mouse stuff
i xorg-xkill \
xsel xclip

# keys/passwords
i gnupg \
pass \
keybase

i klavaro

# torrent
i transmission-gtk

# security

i openssh
i python2-keyring
i python-keyring

# replace ugly default font
i extra/ttf-dejavu
i powerline-fonts

# image manipulation

i scrot \
screenfetch \
libjpeg-turbo gifsicle optipng \
feh eog imagemagick \
gimp \
viewnior

# libre office

i libreoffice-still

# latex

i extra/texlive-bibtexextra \
extra/texlive-bin \
extra/texlive-core \
extra/texlive-fontsextra \
extra/texlive-formatsextra \
extra/texlive-games \
extra/texlive-genericextra \
extra/texlive-htmlxml \
extra/texlive-humanities \
extra/texlive-langchinese \
extra/texlive-langcyrillic \
extra/texlive-langextra \
extra/texlive-langgreek \
extra/texlive-langjapanese \
extra/texlive-langkorean \
extra/texlive-latexextra \
extra/texlive-music \
extra/texlive-pictures \
extra/texlive-plainextra \
extra/texlive-pstricks \
extra/texlive-publishers \
extra/texlive-science

i gnuplot \
xfig transfig \
xorg-xwininfo xorg-xprop

# lesspipe

i lesspipe \
perl \
rpmextract \
fastjar \
unzip \
unrar \
p7zip \
cabextract \
cdrtools \
html2text \
antiword \
unrtf \
imagemagick

# file system

i rclone

# sound

i mpd ncmpcpp

_exit 0
